"""Prompt store contract — custom planner prompt templates (tenant-scoped)."""
from typing import Protocol, runtime_checkable


@runtime_checkable
class PromptStore(Protocol):
    async def create(self, ctx: object, template_id: str, name: str, content: str) -> None: ...
    async def get(self, ctx: object, template_id: str) -> dict | None: ...
    async def update(self, ctx: object, template_id: str, content: str) -> None: ...
    async def delete(self, ctx: object, template_id: str) -> None: ...
    async def list(self, ctx: object) -> list[dict]: ...